[project]
name = "metagoofil"
version = "1.0"
dependencies = [
"google",
"requests",
"argparse",
]

[build-system]
requires = [
    "setuptools",
    "setuptools-scm"
]

[project.scripts]
metagoofil = "metagoofil:main"