[project]
name = "metagoofil"
version = "1.0"
dependencies = [
"google",
"requests",
"argparse",
"os",
"queue",
"random",
"sys",
"threading",
"time",
"urllib",
]

[project.scripts]
metagoofil = "metagoofil:main"